env:
  life:
    name: 'Life-v0'
    update_rate: 1
    timeout: 1000
    max_steps: 2000

  cart:
    name: 'CartPole-v0'

agents:
  cra:
    controller_name: SingleAgentController
    agent_name: CRA
    ac_network: life_network
    td_step: 10
  a2c:
    controller_name: IACController
    agent_name: A2CAgent
    ac_network: ACNetwork
    actor:
      lr: .01
      model_size: 32
    critic:
      lr: .01
      model_size: 32

training:
  timeout: 2000 #
  max_steps: 2000 # steps in one episode before time out, unless not episodic
  eval_rewards_window: 20
