env:
  life:
    name: 'Life-v0'
    update_rate: 1

  cart:
    name: 'CartPole-v0'

agents:
  cra:
    controller_name: SingleAgentController
    agent_name: CRA
    ac_network: life_network
    td_step: 10
  a2c:
    controller_name: IACController
    agent_name: A2CAgent
    actor_network: ActorFCNetwork
    critic_network: CriticFCNetwork
    discount_factor: .99
    entropy_coef: .05
    actor:
      lr: .0001
      model_size: 16
    critic:
      lr: .0001
      model_size: 16

training:
  variation: ''
  n_episodes: 2000 #
  timeout: 2000 # steps in one episode before time out, unless not episodic
  eval_rewards_window: 20
