mobile:
    name: MobileNetV2
    lr: .001
    gradient_clip: 2.5
    train: true # do back prop on encoder
    load_folder: 'networks/trained_weights/MobileNetV2/original/' # ''
    #      [1, 16, 1, 1],  # -8
    #      [6, 24, 2, 2],  # -7
    #      [6, 32, 3, 2],  # -6
    #      [6, 64, 4, 2],  # -5
    #      [6, 96, 3, 1],  # -4
    #      [6, 160, 3, 2],  # -3
    #      [6, 320, 1, 1],  # -2
    last_block: -7 # negative indexing from -8 to -1
    max_block_repeats: 4 # max number of repeats of residual blocks
    pretrained: true # load pretrained trained_weights or not

fc:
    name: MobileNetV2
    lr: .0001
    gradient_clip: 2.5
    train: true # do back prop on encoder
    model_folder: 'networks/trained_weights/MobileNetV2/original/' # ''
    #      [1, 16, 1, 1],  # -8
    #      [6, 24, 2, 2],  # -7
    #      [6, 32, 3, 2],  # -6
    #      [6, 64, 4, 2],  # -5
    #      [6, 96, 3, 1],  # -4
    #      [6, 160, 3, 2],  # -3
    #      [6, 320, 1, 1],  # -2
    last_block: -7 # negative indexing from -8 to -1
    max_block_repeats: 4 # max number of repeats of residual blocks
    pretrained: true # load pretrained trained_weights or not