a2c:
  controller_name: ACController
  agent_name: A2CAgent
  actor_network: ActorFCNetwork
  critic_network: CriticFCNetwork
  share_parameters: ['actor_network', 'critic_network']
  discount_factor: .95
  entropy_coef: .01
  n_threads: 1
  td_step: -1
  actor:
    lr: .001
    model_size: 40
    gradient_clip: 2.5
    use_lstm: true

