grid:
  name: 'Grid-v0'
  update_rate: 1
  n_agents: 1
  bounds: [-1,1]
  timeout: 100
  observations:
    global_resolution: [100, 100]
    observation_window: [199, 199]
    observation_resolution: [33, 33]
    animation_resolution: [100, 100]



# ---------------------------------------------------------------------------
# OPEN AI GYM ENVS
# ---------------------------------------------------------------------------
cart:
  name: 'CartPole-v0'

mountain:
  name: 'MountainCar-v0'

beam:
  name: 'BeamRider-v0'