a2c:
  controller_name: ACController
  agent_name: A2CAgent
  share_parameters: ['actor_network', 'critic_network']
  discount_factor: .95
  entropy_coef: .01
  n_threads: 15
  td_step: -1


  # THESE NAMES KEY INTO CFG_NETWORK.YAML NAMESPACES
  image_encoder:
    name: MobileNetV2
    pretrained: true # load pretrained blueprint_weights or not
    weights_path: 'networks/blueprint_weights/model.pth' # loads config from this folder
    #

    lr: .001
    gradient_clip: 2.5
    train: true # do back prop on encoder
    #      [1, 16, 1, 1],  # -8
    #      [6, 24, 2, 2],  # -7
    #      [6, 32, 3, 2],  # -6
    #      [6, 64, 4, 2],  # -5
    #      [6, 96, 3, 1],  # -4
    #      [6, 160, 3, 2],  # -3
    #      [6, 320, 1, 1],  # -2
    last_block: -7 # negative indexing from -8 to -1
    max_block_repeats: 4 # max number of repeats of residual blocks

  actor_network: ActorFCNetwork
  critic_network: CriticFCNetwork
  actor:
    name: ActorFCNetwork
    lr: .001
    pretrained: false # load pretrained blueprint_weights or not
    model_size: 64
    gradient_clip: 2.5
    use_lstm: false


