grid:
  name: 'Grid-v0'
  update_rate: 1
  n_agents: 1
  bounds: [-1,1]
  timeout: 100
  observations:
    global_resolution: [100, 100]
    observation_resolution: [49, 49]


# ---------------------------------------------------------------------------
# OPEN AI GYM ENVS
# ---------------------------------------------------------------------------
cart:
  name: 'CartPole-v0'

mountain:
  name: 'MountainCar-v0'

beam:
  name: 'BeamRider-v0'